version: '3.8'

services:
  db:
    image: postgres:13
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: lfwallet_development
      POSTGRES_USER: lfwallet
      POSTGRES_PASSWORD: password

  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails server -b 0.0.0.0"
    volumes:
      - ".:/lfwallet"  # Ensure this path matches your Dockerfile WORKDIR
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://lfwallet:password@db/lfwallet_development

volumes:
  postgres-data:
